name: Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.17.x'
          channel: 'stable'
      
      - name: Display flutter version
        run: flutter --version
        
      - name: Get packages
        run: flutter pub get
        
      - name: Analyze the project
        run: flutter analyze
        
      - name: Run tests
        run: flutter test
